INSERT INTO tb_post(title, description, body, created_at) VALUES ('Brasil - 1970', 'A história da seleção que fez história na Copa do México', ' Com estes 11 jogadores como base, o Brasil conquistou a Copa do Mundo em 1970, no México, há exatos 50 anos. Conquistou também o inédito tricampeonato',TIMESTAMP WITH TIME ZONE '2020-09-30');
INSERT INTO tb_post(title, description, body, created_at) VALUES ('A Biografia de Jules Rimet', 'O responsável pela criação da Copa do Mundo', 'Sob a iniciativa de Rimet, foi realizado o primeiro Mundial de Futebol em 1930 e, como forma de homenagem pelo seu papel no campeonato, o troféu recebeu seu nome a partir de 1946: Taça Jules Rimet', TIMESTAMP WITH TIME ZONE '2010-09-20');
INSERT INTO tb_post(title, description, body, created_at) VALUES ('As maiores rivalidades do mundo', 'Ranking realizado baseado na opinião dos mais renomados jornalistas', 'Celtic x Rangers, Roma x Lazio, Real Madrid x Barcelona, Fernebahce x Galatasaray, Boca Juniors x River Plate', TIMESTAMP WITH TIME ZONE '2020-07-28');
INSERT INTO tb_post(title, description, body, created_at) VALUES ('Os frameworks mais utilizados em 2021', 'Levantamento realizado nos principais fóruns de dev', 'Desenvolver um site do zero dá bastante trabalho. Muitas vezes, você vai precisar recriar funções que foram feitas milhares de vezes, o que é tão eficiente quanto reinventar a roda.', TIMESTAMP WITH TIME ZONE '2021-09-30');
INSERT INTO tb_post(title, description, body, created_at) VALUES ('Maiores países do mundo por PIB', 'Brasil deixa o TOP-10', 'O Brasil saiu  do ranking das 10 maiores economias do mundo, de acordo com um levantamento elaborado pela agência de classificação de risco Austin Rating, divulgado no dia 3 de março.', TIMESTAMP WITH TIME ZONE '2020-12-21');
INSERT INTO tb_post(title, description, body, created_at) VALUES ('A criação de Brasília', 'Ideias, planejamento, contra-tempos e custos', 'A construção de Brasília foi uma obra realizada durante o governo de Juscelino Kubitschek e estendeu-se de 1957 a 1960. A transferência da capital do Brasil para o planalto central era parte de um plano idealizado desde o começo da república brasileira', TIMESTAMP WITH TIME ZONE '2020-07-30');
INSERT INTO tb_post(title, description, body, created_at) VALUES ('A história da linguagem Java', 'Desde a criação pela SUN até os dias atuais', 'Java é uma linguagem de programação orientada a objetos desenvolvida na década de 90 por uma equipe de programadores chefiada por James Gosling, na empresa Sun Microsystems', TIMESTAMP WITH TIME ZONE '2018-02-02');


